# -------------------------------------------------------------------------------------
# Author Configuration
# -------------------------------------------------------------------------------------

name = "xucong"
email = "403144966@qq.com"
link = "https://shiqustudio.github.io/"
avatar = "/images/avatar.jpg"
